# Generated by Django 4.0.3 on 2022-04-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='image',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='images',
            field=models.ManyToManyField(blank=True, to='recommendations.image'),
        ),
    ]
