# Generated by Django 4.0.3 on 2022-04-27 13:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_image_remove_recommendation_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
