# Generated by Django 4.0.3 on 2022-04-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_alter_recommendation_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
