# Generated by Django 4.0.3 on 2022-04-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_alter_recommendation_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
