# Generated by Django 4.0.3 on 2022-04-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('salary', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='vacancies/images/')),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time'), ('INTERNSHIP', 'Internship'), ('PROJECT_WORK', 'Project work'), ('VOLUNTEERING', 'Volunteering')], default='INTERNSHIP', max_length=15)),
                ('schedule', models.CharField(choices=[('FULL_DAY', 'Full day'), ('SHIFT_WORK', 'Shift work'), ('SHIFT_METHOD', 'Shift method'), ('REMOTE_WORK', 'Remote work'), ('FLEXIBLE', 'Flexible')], default='FULL_DAY', max_length=15)),
                ('specialization', models.CharField(choices=[('BACK_END', 'Back-end'), ('FRONT_END', 'Front-end'), ('ANDROID', 'Android'), ('IOS', 'iOS'), ('DEVOPS', 'DevOps'), ('NETWORK_ENGINEERING', 'Network Engineering'), ('DATA_ENGINEERING', 'Data Engineering'), ('ML/AI', 'ML/AI'), ('DATA_SCIENCE', 'Data Science'), ('DESKTOP_DEV', 'Desktop app development')], default='BACK_END', max_length=20)),
                ('location', models.CharField(max_length=140)),
            ],
            options={
                'verbose_name_plural': 'Vacancy',
                'ordering': ['-created_on'],
            },
        ),
    ]
