# Generated by Django 4.0.3 on 2022-04-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vacancies/'),
        ),
    ]
