# Generated by Django 4.0.3 on 2022-04-27 13:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_vacancy_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
