# Generated by Django 4.0.3 on 2022-04-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customer_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
