# Generated by Django 4.0.3 on 2022-06-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customer_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-last_login'], 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['id']},
        ),
    ]
