# Generated by Django 4.0.3 on 2022-04-15 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'material type',
                'verbose_name_plural': 'material types',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'IT specialization',
                'verbose_name_plural': 'IT specializations',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=300)),
                ('type', models.ForeignKey(default='read', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='subtopics', to='roadmaps.materialtype')),
            ],
            options={
                'verbose_name': 'subtopic',
                'verbose_name_plural': 'subtopics',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_learned', models.BooleanField(default=False)),
                ('section', models.ManyToManyField(related_name='topics', to='roadmaps.section')),
                ('subtopic', models.ManyToManyField(related_name='topics', to='roadmaps.subtopic')),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='section',
            name='specialization',
            field=models.ManyToManyField(related_name='sections', to='roadmaps.specialization'),
        ),
    ]
