# Generated by Django 4.0.3 on 2022-04-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='skill',
            field=models.ManyToManyField(blank=True, to='users.skill'),
        ),
    ]
