# Generated by Django 4.0.3 on 2022-04-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0003_technology_techstack_alter_materialtype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='techstack',
            field=models.ManyToManyField(blank=True, related_name='specializations', to='roadmaps.techstack'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='topic',
            field=models.ManyToManyField(blank=True, related_name='technologies', to='roadmaps.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subtopic',
            field=models.ManyToManyField(blank=True, related_name='topics', to='roadmaps.subtopic'),
        ),
    ]
