# Generated by Django 4.0.3 on 2022-04-19 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0004_alter_specialization_techstack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='techstack',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subtopic',
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='topics', to='roadmaps.topic'),
        ),
        migrations.AddField(
            model_name='techstack',
            name='specialization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='techstacks', to='roadmaps.specialization'),
        ),
        migrations.AddField(
            model_name='topic',
            name='technology',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='topics', to='roadmaps.technology'),
        ),
    ]
