# Generated by Django 4.0.3 on 2022-04-20 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roadmaps', '0005_remove_specialization_techstack_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.FloatField(default=0)),
                ('technology', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='roadmaps.technology')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userstudies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
