# Generated by Django 4.0.3 on 2022-04-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0006_userstudy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='techstack',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='is_learned',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='technology',
        ),
        migrations.AddField(
            model_name='specialization',
            name='techstacks',
            field=models.ManyToManyField(related_name='specs', to='roadmaps.techstack'),
        ),
        migrations.AddField(
            model_name='technology',
            name='topics',
            field=models.ManyToManyField(related_name='technologies', to='roadmaps.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='subtopics',
            field=models.ManyToManyField(related_name='topics', to='roadmaps.subtopic'),
        ),
    ]
