# Generated by Django 4.0.3 on 2022-04-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0007_remove_specialization_slug_remove_subtopic_topics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='slug',
        ),
    ]
