# Generated by Django 4.0.3 on 2022-04-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0008_remove_topic_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='techstacks',
        ),
        migrations.AddField(
            model_name='specialization',
            name='technologies',
            field=models.ManyToManyField(related_name='specs', to='roadmaps.technology'),
        ),
        migrations.DeleteModel(
            name='Techstack',
        ),
    ]
