# Generated by Django 4.0.3 on 2022-04-27 13:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0009_remove_specialization_techstacks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
