# Generated by Django 4.0.3 on 2022-06-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0012_topic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudy',
            name='topics',
            field=models.ManyToManyField(related_name='user_studies', to='roadmaps.topic'),
        ),
    ]
