# Generated by Django 4.0.3 on 2022-06-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customer_info'),
        ('roadmaps', '0013_userstudy_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='skill',
        ),
        migrations.AddField(
            model_name='topic',
            name='skills',
            field=models.ManyToManyField(blank=True, to='users.skill'),
        ),
    ]
