# Generated by Django 4.0.3 on 2022-06-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0014_remove_technology_skill_topic_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='techs/'),
        ),
    ]
