# Generated by Django 4.0.3 on 2022-06-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0015_technology_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialtype',
            options={'ordering': ('-id',), 'verbose_name': 'Material type', 'verbose_name_plural': 'Material types'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ('-id',), 'verbose_name': 'IT specialization', 'verbose_name_plural': 'IT specializations'},
        ),
        migrations.AlterModelOptions(
            name='subtopic',
            options={'ordering': ('-id',), 'verbose_name': 'Subtopic', 'verbose_name_plural': 'Subtopics'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ('-id',), 'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-id',), 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AlterModelOptions(
            name='userstudy',
            options={'ordering': ('progress',), 'verbose_name': 'User Study Progress', 'verbose_name_plural': 'User Studies Progress'},
        ),
    ]
