# Generated by Django 4.0.3 on 2022-06-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0016_alter_materialtype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
    ]
