# Generated by Django 4.0.3 on 2022-06-15 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0017_alter_topic_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstudy',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userstudies', to='roadmaps.technology'),
        ),
    ]
